# workflow 이름
name : Termial Output Workflow

# 워크플로우를 자동으로 실행할 이벤트를 정의
on:
  # 트리거 : push 이벤트
  push:
    # 실행 조건 브랜치를 설정
    branchs:
      - main

# 실행될 작업(job)들을 정의, job은 워크플로우의 작업 단위
jobs:
  hello-world:
    runs-on:
